services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    # Adding --reload here makes the server restart when you save a file
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./front
    ports:
      - "8080:8080"
    volumes:
      - ./front:/app
